# Generated by Django 4.0.4 on 2022-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('rating', models.IntegerField(verbose_name='4-star rating')),
                ('days', models.IntegerField(verbose_name='5-day tour')),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
